name: 🔒 Security Vulnerability Report
description: Report a security vulnerability in the Laravel Prometheus package
title: "[Security] "
labels: ["security", "vulnerability", "triage"]
assignees:
  - iamfarhad

body:
  - type: markdown
    attributes:
      value: |
        ## Security Vulnerability Report
        
        Thank you for taking the time to report a security vulnerability. We take security seriously and appreciate your responsible disclosure.
        
        **Please do not report security vulnerabilities through public GitHub issues.**
        
        For serious security vulnerabilities, please email: farhad.pd@gmail.com

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: Preliminary Checks
      description: Please verify the following before submitting
      options:
        - label: I have searched for existing security reports
          required: true
        - label: This is a security vulnerability, not a general bug
          required: true
        - label: I understand this should not be a public issue for serious vulnerabilities
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Low (Minor information disclosure)
        - Medium (Moderate impact on security)
        - High (Significant security impact)
        - Critical (Immediate security threat)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Vulnerability Category
      description: What type of vulnerability is this?
      options:
        - Injection (SQL, Command, etc.)
        - Cross-Site Scripting (XSS)
        - Authentication/Authorization
        - Information Disclosure
        - Dependency Vulnerability
        - Configuration Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Provide a clear description of the vulnerability
      placeholder: |
        Describe the vulnerability:
        - What is the issue?
        - How can it be exploited?
        - What is the potential impact?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the vulnerability
      placeholder: |
        1. Install the package with...
        2. Configure...
        3. Execute...
        4. Observe...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Provide details about your environment
      placeholder: |
        - Package Version: 
        - PHP Version: 
        - Laravel Version: 
        - Operating System: 
        - Additional Dependencies: 
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Security Impact
      description: Describe the potential security impact
      placeholder: |
        - What data could be compromised?
        - What systems could be affected?
        - What privileges could be escalated?

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing the vulnerability, please share them
      placeholder: |
        - Potential fixes
        - Workarounds
        - Best practices to prevent similar issues

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your commitment to responsible disclosure
      options:
        - label: I will not publicly disclose this vulnerability until it has been addressed
          required: true
        - label: I will provide reasonable time for the maintainers to fix the issue
          required: true
        - label: I understand this report may be shared with relevant security teams
          required: true
